import './sass/main.scss';
import './js/renderGalleryCards';
import './js/onClickScrollTo';
// import './js/input-country';
import './js/modal-close';
import './js/preloader';
import './js/input-search';
import './js/pagination';
//import './js/more-author';
import './js/variables';
import './js/renderModalInfo';
import './js/markupCountryList';
import './js/select';
import './js/switch';
